import './globals.css';
import type { Metadata } from 'next';
import { Providers } from '@/services/providers/providers';
import React from 'react';
import { ConfigProvider } from 'antd';
import { rootTheme } from '@/config/theme/rootTheme';

export const metadata: Metadata = {
  title: 'Detran',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <ConfigProvider theme={rootTheme}>
          <Providers>
            <>{children}</>
          </Providers>
        </ConfigProvider>
      </body>
    </html>
  );
}
